name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ketan5050
          password: dckr_pat_ORAC9VWVYSu8XO_nTqp26GlBrMs

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ketan5050/dckr_pat_ORAC9VWVYSu8XO_nTqp26GlBrMs:latest
